### PR TITLE
Adds docs generation

### PR DESCRIPTION
**Pull request by shad7**

### CODE REVIEW

**Comment by cdrage** [comment]
Hey @shad7 thanks again for this.

Do you mind if we stick to markdown format instead of rst?

**Comment by shad7** [comment]
I can take a look at what options for generating documentation into markdown instead of rst.

**Comment by shad7** [comment]
Completed using Markdown. Added `make gh-pages`

To be useful, need the `gh-pages` branch created with `index.html`

```
$ git checkout --orphan gh-pages
$ git rm -rf .
$ echo "First commit" > index.html
$ git add index.html
$ git commit -m "Initial commit"
$ git push origin gh-pages
```

**Comment by cdrage** [comment]
Hey @shad7 so I created the branch! What now? Merge this and hope it works?

**Comment by cdrage** [comment]
@shad7 Ahhh I saw from the open issue on how to do this.

I'm going to setup travis soon to have this automatically change on doc changes. Thanks man!

**Comment by shad7** [comment]
I know it works, as I tested all of it locally. I created a branch `gh-pages`, and then I ran the script except for the I commented out the line to attempt to push the branch into Github since I don't have write permissions.

**Comment by cdrage** [comment]
@shad7 Looks like it's up now! https://cdrage.github.io/kubeshift/ just getting .css errors for the _static folder.

**Comment by shad7** [comment]
Looks like I need to get the default templates, css, and js for the theme included to provide the styling.

**Comment by cdrage** [comment]
@shad7 oddly enough, it's actually already in the gh-pages branch (i can see pygments.css, etc.)

**Pull request merged**
