### PR TITLE
refactor and simplify

### PR DESCRIPTION
**Pull request by shad7**

### CODE REVIEW

**Comment by shad7** [comment]
Sharing these changes back in case you have interest. This is a rather large change so I don't expect this to get merged. thanks

**Comment by cdrage** [comment]
Woah, that's *a lot*, will take me a while to process this and go through it all. You should hear back from me later this week.

Thanks a lot man for the contribution(s). Only thing I don't like from it is using minikube instead of Docker (makes it easier for running integration tests on travis).

Thanks a lottt!

**Comment by shad7** [comment]
I realized the integration tests was intended for travis after submitting the PR. I had switched to mini* to make it work locally in a consistent fashion. That part could easily tweak to leverage docker directly for travis.

**Comment by shad7** [comment]
Added the integration via docker when executing via TRAVIS. To simulate locally, just `export TRAVIS=true`

Works under python3.4 and python3.5 as well.

**Comment by cdrage** [comment]
@shad7 
I see that `Client` is removed.

Are you able to provide a quick explanation on how to use / run this now? :) May have to update the examples/kubernetes.py we have. 

I see that a lot of the code for the explicit functions for the API is gone.

Thanks again for all the hard work!

**Comment by shad7** [comment]
The `Client` was just a wrapper and required you to pass in a text string to indicate which implementation was required. Therefore simply exposing `KubernetesClient` and `OpenshiftClient` directly there is no need for the string or to check if the wrong value was passed in. The user/consumer just instantiates the client they intend to use.

All the same APIs exist as before, they are just there via mixin pattern and inheritance.

The class `_ClientBase` provides the basic core of executing any request (aka the formatting of the URL and the actual initiating the request, and common configuration). 

The class `KubeBase` inherits/extends from `_ClientBase` and all the read/query APIs are added via the class `QueryMixin`. Then `KubeBase` provides the other parts of CRUD that already existed, aka create, delete, and scale (the only update option). 

The class `KubernetesClient` inherits from `KubeBase`, therefore there is no specific implementation that is different from the base, but provides the user friendly client name to use.

The class `OpenshiftClient` inherits from `KubeBase`, therefore having all the same capabilities as the `KubernetesClient`. The `OpenshiftClient` does have some implementation details to support the additional APIs provided via Openshift that are above and beyond the Kubernetes. The additional APIs loaded and the support for Templates is currently the only specific implementation details currently. 

The other major refactoring was around the handling of kube config. The class provides the 2 basic class methods that existed before, `from_file` and `from_params`. The access to the contents is all managed within the `Config` class instance. The only use internally to kubeshift is calling `format_session` to get the values needed to to create a connection.

The usage is (or should be) the same as before generally speaking.

```python
import kubeshift

k8s_object = {"apiVersion": "v1", "kind": "Pod", "metadata": {"labels": {"app": "helloapache"}, "name": "helloapache"}, "spec": {
    "containers": [{"image": "nginx", "name": "helloapache", "ports": [{"containerPort": 80, "hostPort": 80, "protocol": "TCP"}]}]}}

# passing in None as the file, it will default to `$HOME/.kube/config`
client = kubeshift.KubernetesClient(kubeshift.Config.from_file(None))
client.create(k8s_object)
client.delete(k8s_object)

# Pods
client.pods().all()
client.pods().filter(namespace="default", status="Running")
client.pods().metadata()
client.pods().items()
```

**Comment by shad7** [comment]
Also on the use of Config. When passed into the client, it will accept the following formats:

- `Config` class instance, created by calling `kubeshift.Config.from_file` or `kubeshift.Config.from_params`
- `dict` to align with what previously was passed into it (helps alot in testing); the client will just instantiate the `Config` instance using the `dict` as the contents of a parsed kube config file.
- `str` which is assumed to be the file path to the kube config file; the client will just instantiate the `Config` instance using `Config.from_file`.

in the example, it could easily be changed to:

```
# passing in None as the file, it will default to `$HOME/.kube/config`
client = kubeshift.KubernetesClient(None)
```
The result would be the same as the example I provided previously.

The intent is to be flexible enough for users but making sure we always end up with a `Config` instance.

**Comment by shad7** [comment]
The history behind this change. And why I did all of this over the weekend :)

This all started as I was building Ansible modules for working with Openshift, and the single most important element was the kube config. I used ideas from here and `pykube` to construct a single KubeConfig class. You will notice the ability to update and write the config file. Since your focus was on supporting both Kubernetes and Openshift, this seemed like the better direction to go. That would make it easier to create a foundation that existing Ansible module `kubernetes` and the `openshift` could leverage to perform tasks against either type of cluster. 

I'm considering adding `login` method here, so that I could then further simplify the logic within the Ansible module `openshift_login`.

**Comment by cdrage** [comment]
I'm going to go ahead and start reviewing this :)

**Pull request merged**
