### PR TITLE
Feature/byfile

### PR DESCRIPTION
**Pull request by shad7**

### CODE REVIEW

**Comment by shad7** [comment]
Extends PR #34 

As the return of results is very useful for this change as well.

**Comment by cdrage** [comment]
@shad7 Thanks man! So one thing to note, and maybe this may need to be changed back to using `anymarkup`. But the problem is that Kubernetes artifacts / resource files could either be JSON or YAML. This only accounts for yaml :(. Is there a possibility that we could perhaps switch *back* to using anymarkup instead of pyyaml for parsing?

If there are any other alternatives, I'm open to suggestions!

**Comment by shad7** [comment]
@cdrage Yaml is a superset over json, so the Yaml parser can and does parse json as well. There are tests showing the parsing of json files using the PyYaml parser as it loads properly.

**Comment by cdrage** [comment]
@shad7 I'm an idiot. Thanks man!

**Pull request merged**
